### ISSUE TITLE
GMEHelper error in Blender

### ISSUE THREAD

**Issue by KilianMeier** [meereuk/GMEHelper#1]
![error](https://user-images.githubusercontent.com/48472506/148647539-617a9767-3f84-4d7a-8f51-b75e170e3bc0.PNG)
Hi,
When i choose Assign basic materials in GMEHelper i get this error. I tried it with a vanilla character in HS2 and 2 other characters with mods. 

I also have another issue. When i try to apply the skin texture manually in blender the Main skin png is always black. I also tried this with a few characters.
![skin](https://user-images.githubusercontent.com/48472506/148648010-36775f03-488d-499e-89b0-a6896833eb95.PNG)

**Comment by meereuk** [comment]
Sorry for being late. First, make sure your body object name is "cf_O_body"; in certain circumstances, it may have a different name.
And I don't have an idea for that black texture, just from that picture.

**Comment by KilianMeier** [comment]
Sorry, i also am writing late. It seems some objects are japanese when you export them, that is the reason for the script not able being to detect them, i looked them up in translate and corrected the parts with the names in the script. Thanks again.
